// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5VqrtYgSLUl_f5G7ahRqfWEy3h5X2bc',
    appId: '1:557559761461:web:29be5f139f3f3d61af3f7c',
    messagingSenderId: '557559761461',
    projectId: 'device-streaming-467b96f6',
    authDomain: 'device-streaming-467b96f6.firebaseapp.com',
    storageBucket: 'device-streaming-467b96f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtcp2E8bCoNOruant0MPtCJwgi7vUXsuE',
    appId: '1:557559761461:android:f7bc92415ea50fbdaf3f7c',
    messagingSenderId: '557559761461',
    projectId: 'device-streaming-467b96f6',
    storageBucket: 'device-streaming-467b96f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GEXU8tRmrsC_oM5AZ4mBGqWEe0cBF1Q',
    appId: '1:557559761461:ios:e5b0def6ab3a8465af3f7c',
    messagingSenderId: '557559761461',
    projectId: 'device-streaming-467b96f6',
    storageBucket: 'device-streaming-467b96f6.firebasestorage.app',
    iosBundleId: 'com.example.fermentpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8GEXU8tRmrsC_oM5AZ4mBGqWEe0cBF1Q',
    appId: '1:557559761461:ios:e5b0def6ab3a8465af3f7c',
    messagingSenderId: '557559761461',
    projectId: 'device-streaming-467b96f6',
    storageBucket: 'device-streaming-467b96f6.firebasestorage.app',
    iosBundleId: 'com.example.fermentpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk5VqrtYgSLUl_f5G7ahRqfWEy3h5X2bc',
    appId: '1:557559761461:web:2f59cbeda53fb5f5af3f7c',
    messagingSenderId: '557559761461',
    projectId: 'device-streaming-467b96f6',
    authDomain: 'device-streaming-467b96f6.firebaseapp.com',
    storageBucket: 'device-streaming-467b96f6.firebasestorage.app',
  );
}
